###############################################################################
# Makefile for gcc 6.5.0b (from Bebbo)
###############################################################################

CC  := /opt/amiga/bin/m68k-amigaos-gcc
OS  := ks13

ifneq ($(lastword $(MAKEFILE_LIST)),Makefile.650)
MAKEFILE_LIST += Makefile.650
endif

include Makefile

OFLAGS = -Ofast

# there do not seem to be any support for stackexend, so ignore it
STACKEXTEND =
LDFLAGS += -m$(CPU) -Wl,--allow-multiple-definition

do_tst_%:
	@true
