##############################################################################
# Makefile for vbcc targetting 68k AmigaOS
##############################################################################

CC     := vc +aos68k

ifneq ($(lastword $(MAKEFILE_LIST)), Makefile.vbcc-aos)
MAKEFILE_LIST += Makefile.vbcc-aos
endif
include Makefile.vbcc

CFLAGS += -cpu=$(CPU)
