##############################################################################
# Makefile for vbcc targetting ppc MorphOS
##############################################################################

CC          := vc +morphos
CPU         := ppc
OS          := morphos
RUNNING_AOS := 1

ifneq ($(lastword $(MAKEFILE_LIST)),Makefile.vbcc-mos)
MAKEFILE_LIST += Makefile.vbcc-mos
endif
include Makefile.vbcc

LIBS    = -lamiga -lm
OFLAGS += -use-lmw
