##############################################################################
# Makefile for vbcc targetting ppc MorphOS
##############################################################################

CC     := vc +morphos
OS     := morphos
CPU    := ppc
OBJDIR := obj$(CPU)
NATIVE := 1

EXT    := vbccppc

ifneq ($(lastword $(MAKEFILE_LIST)), Makefile.vbcc-mos)
MAKEFILE_LIST += Makefile.vbcc-mos
endif
include Makefile.vbcc

LIBS    = -lamiga -lm
OFLAGS += -use-lmw
