###############################################################################
# Makefile for gcc 3.2.2 (from GG)
###############################################################################

CC  := gg:bin/gcc
OS  := AmigaOS

ifneq ($(lastword $(MAKEFILE_LIST)),Makefile.322)
MAKEFILE_LIST += Makefile.322
endif

include Makefile

LDFLAGS += -m$(CPU)